//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyAutoInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int Id { get; set; }
        public Nullable<decimal> BaseCost { get; set; }
        public Nullable<decimal> Under25YO { get; set; }
        public Nullable<decimal> Under18YO { get; set; }
        public Nullable<decimal> Over100YO { get; set; }
        public Nullable<int> OldCarYear { get; set; }
        public Nullable<decimal> OldCarCost { get; set; }
        public Nullable<int> NewCarYear { get; set; }
        public Nullable<decimal> NewCarCost { get; set; }
        public Nullable<decimal> PerSpeedingTicketCost { get; set; }
        public Nullable<int> FullCoveragePercent { get; set; }
        public Nullable<decimal> DUIPercent { get; set; }
    }
}
