//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyAutoInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakeCost
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public Nullable<decimal> MakeCost1 { get; set; }
    }
}
